---
- name: ovn4nfv | Label control-plane node
  command: >-
    {{ kubectl }} label --overwrite node {{ groups['kube_control_plane'] | first }} ovn4nfv-k8s-plugin=ovn-control-plane
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

