---
- name: CRI-O | Kubic repo name for debian os family
  set_fact:
    crio_kubic_debian_repo_name: "{{ ((ansible_distribution == 'Ubuntu') | ternary('x','')) ~ ansible_distribution ~ '_' ~ ansible_distribution_version }}"
  when: ansible_os_family == "Debian"
  tags:
    - reset_crio

- name: CRI-O | Remove kubic apt repo
  apt_repository:
    repo: "deb http://{{ crio_download_base }}/{{ crio_kubic_debian_repo_name }}/ /"
    state: absent
  when: crio_kubic_debian_repo_name is defined
  tags:
    - reset_crio

- name: CRI-O | Remove cri-o apt repo
  apt_repository:
    repo: "deb {{ crio_download_crio }}{{ crio_version }}/{{ crio_kubic_debian_repo_name }}/ /"
    state: present
    filename: devel-kubic-libcontainers-stable-cri-o
  when: crio_kubic_debian_repo_name is defined
  tags:
    - reset_crio

- name: CRI-O | Remove CRI-O kubic yum repo
  yum_repository:
    name: devel_kubic_libcontainers_stable
    state: absent
  when: ansible_distribution in ["Amazon"]
  tags:
    - reset_crio

- name: CRI-O | Remove CRI-O kubic yum repo
  yum_repository:
    name: "devel_kubic_libco