---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install xfs package
- name: install xfs Debian
  apt: name=xfsprogs state=present
  when: ansible_os_family == "Debian"

- name: install xfs RedHat
  package: name=xfsprogs state=present
  when: ansible_os_family == "RedHat"

# Format external volumes in xfs
- name: Format volumes in xfs
  filesystem: "fstype=xfs dev={{ disk_volume_device_1 }}"

# Mount external volumes
- name: mounting new xfs filesystem
  mount: "name={{ gluster_volume_node_mount_dir }} src={{ disk_volume_device_1 }} fstype=xfs state=mounted"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure GlusterFS is started and enabled at boot.
  service: "name={{ glusterfs_daemon }} state=started enabled=yes"

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_ite